[package]
name = "allan-tools"
version = "0.0.1"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]

homepage = "https://github.com/gwbres/allan-tools"
readme = "README.md"
keywords = ["allan", "variance", "deviation", "stability", "time", "frequency"]

[dev-dependencies]
probability = "0.15.8"
rand = "0.3.16"
